---
development:
  cloud_name: lionshare
  api_key: '655886391515878'
  api_secret: nr-TxXQDsnBRl93PJrURe7EHbnc
production:
  cloud_name: lionshare
  api_key: '655886391515878'
  api_secret: nr-TxXQDsnBRl93PJrURe7EHbnc
test:
  cloud_name: lionshare
  api_key: '655886391515878'
  api_secret: nr-TxXQDsnBRl93PJrURe7EHbnc
