---
development:
  cloud_name: deeqeoofc
  api_key: '558878175797216'
  api_secret: 4C5_cQIF8DWLOpnfOPEwbVLsPRU
production:
  cloud_name: deeqeoofc
  api_key: '558878175797216'
  api_secret: 4C5_cQIF8DWLOpnfOPEwbVLsPRU
test:
  cloud_name: deeqeoofc
  api_key: '558878175797216'
  api_secret: 4C5_cQIF8DWLOpnfOPEwbVLsPRU
